service: serverless
frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: dev

functions:
  test:
    handler: src/handler.run
    events:
      - schedule: cron(* * * * ? *)
