service: serverless

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  env: ${file(./.env.${opt:stage, 'dev'}.json)}

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - ${self:custom.env.SG_ID}
    subnetIds:
      - ${self:custom.env.SUBNET_ID}
  timeout: 900
  environment:
    TEST_KEY: ${self:custom.env.TEST_KEY}

functions:
  test:
    handler: src/handler.run
    events:
      - schedule: cron(* * * * ? *)
